version: "3.8"
services:
  node:
    build: "."
    image: sv-mosaic:local
    volumes:
      - "./src:/app/src"
      - "./testing:/app/testing"
      - "./.storybook:/app/.storybook"
      - "./scripts:/app/scripts"
      - "./dist:/app/dist"
      - "./package.json:/app/mounted/package.json"
      - "./yarn.lock:/app/mounted/yarn.lock"
      - "./.yarn:/app/mounted/.yarn"
      - "./webpack.config.js:/app/webpack.config.js"
      - "./.babelrc:/app/.babelrc"
      - "./tsconfig.json:/app/tsconfig.json"
      - "./tsconfig.cjs.json:/app/tsconfig.cjs.json"
      - "./tsconfig.esm.json:/app/tsconfig.esm.json"
      - "./.eslintrc.json:/app/.eslintrc.json"
      - "./.eslintignore:/app/.eslintignore"
      - "./jest.config.js:/app/jest.config.js"
    ports:
      - "10000:10000"
  automation_testing:
    build: "./automation_testing"
    image: sv-mosaic:automation_testing
    ports:
      - "20000:20000"
    depends_on:
      - "node"
