version: 2.1
vars:
  setup_remote_docker: &setup_remote_docker
    setup_remote_docker:
      docker_layer_caching: true
      version: 20.10.14
  load_build_image: &load_build_image
    run:
      name: Import build image
      command: docker load -i workspace/build/sv-mosaic-local.tar.gz
  # setup_environment: &setup_environment
  #     run:
  #         name: Setup Environment Variables
  #         command: |
  #           echo 'export IMAGE="gcr.io/sv-shared-231700/sv-mosaic:${CIRCLE_BRANCH}"' >> $BASH_ENV
  # docker_login: &docker_login
  #     run:
  #         name: Docker Login
  #         command: |
  #           docker login -u _json_key -p "${GCLOUD_SERVICE_KEY}" https://gcr.io
workflows:
  build:
    jobs:
      - build:
          context: default
          filters:
            branches:
              only:
                - develop
                - master
                - qa
                - staging
                - /pull.*/
      - publish:
          context: default
          requires:
            - build
          filters:
            branches:
              only:
                - qa
                - staging
                - master
      - storybook:
          context: default
          requires:
            - build
      - unit_tests:
          context: default
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /pull.*/
      - automation_tests:
          context: default
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
                - qa
                - staging
                - /pull.*/

orbs:
  slack: circleci/slack@4.4.0
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - *setup_remote_docker
      - run:
          name: Build
          command: docker compose build node
      - run:
          name: Save to file
          command: |
            mkdir -p workspace
            docker save sv-mosaic:local | gzip > workspace/build/sv-mosaic-local.tar.gz
    persist_to_workspace:
      root: /workspace/build/
      paths: sv-mosaic-local.tar.gz
  publish:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - *setup_remote_docker
      - *load_build_image
      - run:
          name: Publish to NPM
          command: docker compose run --rm node_ci yarn run ci:publish
  storybook:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    steps:
      - checkout
      - *setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - 90:c4:82:92:d0:82:28:9d:f4:c9:d0:25:27:1e:07:50
      - *load_build_image
      - run:
          name: Add github to known_hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Publish storybook
          command: docker compose run --rm node yarn run ci:storybook
          environment:
            NODE_DEBUG: gh-pages
  unit_tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    attach_workspace:
      at: workspace
    steps:
      - checkout
      - *setup_remote_docker
      - *load_build_image
      - run:
          name: Unit tests
          command: docker compose run -rm node yarn test
  automation_tests:
    docker:
      - image: cimg/base:2021.04
    resource_class: large
    attach_workspace:
      at: workspace
    steps:
      - checkout
      - *setup_remote_docker
      - *load_build_image
      - run:
          name: Build
          command: docker compose build automation_testing

      - run:
          name: Automation tests
          command: docker compose run -rm automation_testing ENV=local npm run test:chrome
